# Generated by Django 4.2.3 on 2023-07-06 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Assigned'), (2, 'At Vendor'), (3, 'Picked'), (4, 'Delivered')], db_index=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='order.order')),
            ],
        ),
    ]
