# Generated by Django 4.2.3 on 2023-07-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Assigned'), (2, 'At Vendor'), (3, 'Picked'), (4, 'Delivered')], db_index=True)),
            ],
        ),
    ]
