stages:
  - test

test:
  stage: test
  image: python:3.11
  variables:
    DB_DATABASE: sfdr
    DB_ROOT_PASSWORD: sfdr
    DB_USER: sfdr
    DB_PASSWORD: sfdr

    MIN_COVERAGE: 55


  services:
    - postgres:latest
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install -r requirements/dev.txt
    - cp env.ci .env
  script:
    - coverage run manage.py test
    - coverage report --fail-under $MIN_COVERAGE
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - merge_requests

flake8:
  stage: test
  script:
    - flake8 .
  only:
    - merge_requests
