version: "3.7"
services:
  test:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        echo "Sleeping till db ready to accept connection!"
        sleep 3
        echo "Running test ..."
        python manage.py test --noinput
    env_file: environments/production.env
    depends_on:
      - db
    restart: 'no'
    networks:
      - sfdr_global
  web:
    build: .
    restart: always
    command: /bin/bash -c "/entry_point.sh"
    env_file: environments/production.env
    volumes:
      - static:/static
      - socket:/socket
    depends_on:
      - db
      - redis
      - test
      - nginx
      - rabbitmq

    links:
      - db
      - redis
    networks:
      - sfdr_global
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_username
      - RABBITMQ_DEFAULT_PASS=rabbit_password
      - RABBITMQ_DEFAULT_VHOST=dear_vhost
    ports:
      - "5672:5672"
      - "15450:15672"
    networks:
      - sfdr_global
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=sfdr
      - POSTGRES_USER=sfdr
      - POSTGRES_PASSWORD=sfdr
    ports:
      - "6000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sfdr_global
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6200:6379"
    networks:
      - sfdr_global
  celery:
    build: .
    command: celery -A SFDR worker --beat --scheduler django --loglevel=info --logfile=celery.log
    env_file: environments/production.env
    restart: always
    links:
      - redis
      - db
    networks:
      - sfdr_global

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:8080"
    volumes:
      - socket:/socket
      - static:/static
    networks:
      - sfdr_global

volumes:
  db_data:
  redis_data:
  socket:
  static:

networks:
  sfdr_global:
    external: true
