# Generated by Django 4.2.3 on 2023-07-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
    ]
