# Generated by Django 4.2.3 on 2023-07-06 18:52

from django.db import migrations, models
import django.db.models.deletion
import utils.fakers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=utils.fakers.fake_name, max_length=100)),
                ('delivery_time', models.PositiveBigIntegerField(help_text='Preparation and shipping time')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_reports', to='order.order')),
            ],
        ),
    ]
