# Generated by Django 4.2.3 on 2023-07-06 20:27

from django.db import migrations, models
import django.db.models.deletion
import utils.fakers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=utils.fakers.fake_name, max_length=100)),
                ('deliver_at', models.DateTimeField(db_index=True, default=utils.fakers.fake_delivery_time)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Shipping Time Updated'), (2, 'Inserted Into Queue'), (3, 'Rejected')], db_index=True)),
                ('delay', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(null=True)),
                ('sate', models.PositiveSmallIntegerField(choices=[(0, 'In Queue'), (1, 'Assigned To Vendor'), (2, 'Checked')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_reports', to='order.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='vendor.vendor')),
            ],
        ),
    ]
