# Generated by Django 4.2.3 on 2023-07-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelayreport',
            name='sate',
        ),
        migrations.AddField(
            model_name='orderdelayreport',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Need To Action'), (1, 'Waiting For Agent'), (2, 'Assigned To Vendor'), (3, 'Checked')], db_index=True, default=0),
        ),
    ]
