# Generated by Django 4.2.3 on 2023-07-06 18:36

from django.db import migrations, models
import faker.providers.person


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trip',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=100),
        ),
    ]
