# Generated by Django 4.2.3 on 2023-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderdelayreport_sate_orderdelayreport_state'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderdelayreport',
            constraint=models.CheckConstraint(check=models.Q(('agent_id', models.F('agent_id')), ('state', 2)), name='unique_assigned_delay_report_to_one_agent', violation_error_message='Agent already has an assigned delay report!'),
        ),
    ]
